# Generated by Django 5.1.4 on 2024-12-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='filamentdetails',
            options={'verbose_name': 'Filament detail', 'verbose_name_plural': 'Filament details'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterField(
            model_name='filamentdetails',
            name='material',
            field=models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU'), ('PET', 'PET'), ('PST', 'PST'), ('CF-Reinforced', 'CF-Reinforced')], max_length=30),
        ),
        migrations.AlterField(
            model_name='filamentdetails',
            name='product',
            field=models.OneToOneField(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='filament_details', to='printshop.product'),
        ),
    ]
