# Generated by Django 5.1.4 on 2025-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(default=False, help_text='Mark as blocked to prevent user login.'),
        ),
    ]
