# Generated by Django 5.1.4 on 2025-01-07 14:43

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

def create_moderatori_group(apps, schema_editor):
    # Get the CustomUser model
    CustomUser = apps.get_model('printshop', 'CustomUser')

    # Create Moderatori group
    group, created = Group.objects.get_or_create(name='Moderatori')

    # Assign permissions
    content_type = ContentType.objects.get_for_model(CustomUser)
    permissions = Permission.objects.filter(content_type=content_type, codename__in=[
        'view_customuser',  # View user data
        'change_customuser',  # Edit name, email, etc.
    ])
    group.permissions.add(*permissions)

class Migration(migrations.Migration):
    dependencies = [
        ('printshop', 'previous_migration_name'),
    ]

    operations = [
        migrations.RunPython(create_moderatori_group),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0002_customuser_blocat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(default=False, help_text='Mark as blocked to prevent user login'),
        ),
    ]
